### ISSUE TITLE
Main page Download button not working

### ISSUE THREAD

**Issue by halabiroger** [sixem/tiktok-download-buttons#10]
Just want to report this minor issue, but the download button for videos on the Main page doesn't work for any video.  Attached is a screenshot example.

![Main page download button](https://user-images.githubusercontent.com/109829436/230414316-51ff17dd-d342-47cd-bb45-41e3fb348bdf.jpg)

**Comment by sixem** [comment]
I can't reproduce this, they work fine on my end.

Do you get any messages at all or is there just no action when clicking it? Does it persist if you don't have a template set?

Also, if you could open the `service worker` here:

![image](https://user-images.githubusercontent.com/2825338/230415177-92f2423f-f932-4fe2-8b3c-cd9de48c21de.png)

And then see if you get any messages in the `Console` tab when you are attempting to dowload a video.

**Comment by halabiroger** [comment]
> I can't reproduce this, they work fine on my end.
> 
> Do you get any messages at all or is there just no action when clicking it? Does it persist if you don't have a template set?
> 
> Also, if you could open the `service worker` here:
> 
> ![image](https://user-images.githubusercontent.com/2825338/230415177-92f2423f-f932-4fe2-8b3c-cd9de48c21de.png)
> 
> And then see if you get any messages in the `Console` tab when you are attempting to dowload a video.

Sorry for alarming you, it's working now, not sure what change. The download button would just spin and spin and spin with no error.

**Comment by sixem** [comment]
All good!

This addon does use the official API which can be a bit clunky at times, so errors may happen from time to time. We're not really supposed to use it, but it's the only official way of downloading non-watermarked videos. Could also have just been a short network error of some sort.
