### ISSUE TITLE
Download icon not showing

### ISSUE THREAD

**Issue by vascogomesucpt** [sixem/tiktok-download-buttons#12]
Hi, the download buttons are not showing, for example on the feed (For You)

Greetings.

**Comment by sixem** [comment]
Hi, I can't seem to reproduce this issue. The buttons are visible on my end.

If you don't mind, could you provide me with the location you are trying to access TikTok from as well as the browser you're using? It's possible that they are rolling out different layouts for differnet regions, so that can be a way for me to reproduce it, possibly.

**Comment by sixem** [comment]
> Discovered. This doesn't exist on the tiktok DOM: [class^="tiktok-"]

It could be that they've changed the HTML structure for some regions, it has happened before. I need a way to reproduce it though, so that I can fix it and confirm that it actually works. I can try with a few VPNs later on, to see if I can replicate your issues.

The class selectors are here if you are curious:
https://github.com/sixem/tiktok-download-buttons/blob/671ac826a468e49fd10dc66fdd81647398634e35/main.js#L1443-L1457

**Comment by halabiroger** [comment]
As of today, it looks like Tiktok web changed something because download icon doesn't show anymore.

**Comment by sixem** [comment]
> As of today, it looks like Tiktok web changed something because download icon doesn't show anymore. I think maybe after I upgraded Chrome to Version 115.0.5790.99 late yesterday.

I'm able to reproduce this in Chrome at least. It looks like some of the HTML structure has been changed. I'll take a look at it ASAP.

**Comment by halabiroger** [comment]
> > As of today, it looks like Tiktok web changed something because download icon doesn't show anymore. I think maybe after I upgraded Chrome to Version 115.0.5790.99 late yesterday.
> 
> I'm able to reproduce this in Chrome at least. It looks like some of the HTML structure has been changed. I'll take a look at it ASAP.

Thx appreciate it.

**Comment by sixem** [comment]
> > > As of today, it looks like Tiktok web changed something because download icon doesn't show anymore. I think maybe after I upgraded Chrome to Version 115.0.5790.99 late yesterday.
> > 
> > 
> > I'm able to reproduce this in Chrome at least. It looks like some of the HTML structure has been changed. I'll take a look at it ASAP.
> 
> Thx appreciate it.

I've made some changes which should fix it.

If you have the opportunity to test the source code, that'd be great, but if not — that's fine too. Either way, I'll test it a bit more tomorrow myself, and then hopefully submit the update.

**Comment by halabiroger** [comment]
> > > > As of today, it looks like Tiktok web changed something because download icon doesn't show anymore. I think maybe after I upgraded Chrome to Version 115.0.5790.99 late yesterday.
> > > 
> > > 
> > > I'm able to reproduce this in Chrome at least. It looks like some of the HTML structure has been changed. I'll take a look at it ASAP.
> > 
> > 
> > Thx appreciate it.
> 
> I've made some changes which should fix it.
> 
> If you have the opportunity to test the source code, that'd be great, but if not — that's fine too. Either way, I'll test it a bit more tomorrow myself, and then hopefully submit the update.

Sorry but not able to test until the new version is available in the Chrome store to download.

**Comment by sixem** [comment]
I've submitted the update to both Chrome and Firefox now.

I'll leave this issue open for a bit just in case there are any more issues. The review process can take anywhere from a few hours to a few days, so I don't know when it wil be live, but it shouldn't take too long.

**Comment by halabiroger** [comment]
> I've submitted the update to both Chrome and Firefox now.
> 
> I'll leave this issue open for a bit just in case there are any more issues. The review process can take anywhere from a few hours to a few days, so I don't know when it wil be live, but it shouldn't take too long.

I can confirm both download buttons in v1.1.4 are working now. Thank you for your efforts and time.

**Comment by halabiroger** [comment]
> It's happening again. On the main feed download button not showing.

I see the download button and it works when I click it on a users list of videos main feed page.

**Comment by halabiroger** [comment]
> Maybe it's the same as last time. They update the interface on some regions (Europe) first and then later the rest of the world, so works for some people and don't work for others. Greetings.

Not sure, but it's working for me in the US.
