### ISSUE TITLE
Blob downloading without watermark

### ISSUE THREAD

**Issue by swaglogger** [sixem/tiktok-download-buttons#14]
Chrome version: 115.0.5790.171

I have the checkbox off for prioritize api download. I see it downloads successfully as blob without the watermark. I do see in chrome download bar that there is a failed downloads then a correct redownload if that helps.

**Comment by sixem** [comment]
Blobs weren't that common when I first made this addon, so I haven't been able to test it that much so far (there's also not much demand for it when most just use the API), but I think there's an issue with how Blobs are being saved (they can be tricky when we're downloading from a service script), hence why it initially fails, then falls back to the API. When I have some time, I'll look into it, to see if I can find a better method of saving Blobs directly.

**Comment by swaglogger** [comment]
Any update on this?

**Comment by sixem** [comment]
> Any update on this?

Sorry, been quite busy lately. I'll see if I can take a look at it this week.

Just to clarify, you want Blob videos to download without the watermark if the "Prioritize API download" is unchecked? And the problem is that it always falls back on the API which obviously gives you the video without the watermark?

**Comment by swaglogger** [comment]
> Just to clarify, you want Blob videos to download without the watermark

I'd like blob with the watermark. And yes current behavior it always falls back to api which has no watermarks

**Comment by sixem** [comment]
> > Just to clarify, you want Blob videos to download without the watermark
> 
> I'd like blob with the watermark. And yes current behavior it always falls back to api which has no watermarks

So, I was looking a bit into it last week, and I think I'll have to find a workaround for download Blobs (or finding the non-blob source somehow), as they don't appear to be easily fetchable in the current browser context.

But, regarding your original issue, the Blob videos won't have watermarks either way on the desktop version (they'll just be of a lower quality than the one fetched from the API, but still _without_ watermark), and there is a built-in way in TikTok's own site for downloading the videos with the watermark. So, my question is, what's wrong with just downloading it using TikTok's own downloader if you specifically want the watermarks?

**Comment by swaglogger** [comment]
Tiktok doesn't always allow native downloads depending on the account it seems. 

My use case is really just the ease of access to download many videos quickly using the download button overlayed on the preview using the addon. I can quickly just click from the thumbnails for the vids that I want to save. I guess for me it actually doesn't matter if its api or blob. Just need the watermark with it. I know it's a very unusual request that no one else really needs so no problem if it's unsolvable

**Comment by swaglogger** [comment]
No longer needed

**Comment by swaglogger** [comment]
No longer needed
