### ISSUE TITLE
Access Denied issue 

### ISSUE THREAD

**Issue by wombat2024** [sixem/tiktok-download-buttons#16]
Hi sixem, the extension stopped working this week, when I try to download any video it redirects to url like
https://v16-webapp-prime.tiktok.com/video/tos/alisg/tos-alisg-pve-0037c001/o4ygUGQYEujUAn1CIICEtAAkQIfx7otgUwczGh/...
which page shows

> Access Denied
> You don't have permission to access "http://v16-webapp-prime.tiktok.com/video/tos/alisg/tos-alisg-pve-0037c001/o4ygUGQYEujUAn1CIICEtAAkQIfx7otgUwczGh/?" on this server.
> 
> Reference #18.14cd387d.1710573293.271cf45 

tried both chrome and firefox, please have a look when available, thanks!

**Comment by sixem** [comment]
This is the fallback functionality for when the API fails, and it doesn't always work. Basically it'll just try to open the actual raw video URL instead, as fetched through the HTML.

I've updated the API URL and submitted the updates now, so _hopefully_ that should fix it. I'll leave this open for a bit in case of any new issues.

**Comment by wombat2024** [comment]
Yes it's working like a charm, much appreciated 🤩

**Comment by wombat2024** [comment]
Hi @sixem I've found that usually when certain video fails to download with access denied error, other downloadable videos will also fail to download for a period of time (then become downloadable again), just wonder that how long is this period and is it possible to avoid this? Thanks!

**Comment by wombat2024** [comment]
Actually I sorta figured out a way to circumnavigate this situation, previously when I clicked the download button of certain video, if the download button hangs a few seconds spinning I know it's undownloadable (because usually it starts downloading instantly), then I could simply close that browser tab and reopen, and it'll not affect other videos to download. 

However since the latest version when a video download fails it fails immediately (without button spinning), which makes it impossible for me to preemptively close the tab before it causes other videos to be undownloadable..

**Comment by sixem** [comment]
> Actually I sorta figured out a way to circumnavigate this situation, previously when I clicked the download button of certain video, if the download button hangs a few seconds spinning I know it's undownloadable (because usually it starts downloading instantly), then I could simply close that browser tab and reopen, and it'll not affect other videos to download.
> 
> However since the latest version when a video download fails it fails immediately (without button spinning), which makes it impossible for me to preemptively close the tab before it causes other videos to be undownloadable..

Yeah, once an API fails (it attempts a few times during the same download with a few different version parameters set), there will be a flag that tells it not to use the API until a set amount of time has passed. I think it's somewhere around 15 minutes. This is probably why it hangs on downloading, as it is attempting like 4-5 requests before giving up, I think, and when the flag/cooldown is active, this entire process is skipped. Why the behavior has changed since the last update, I don't know, and I'll have to have a look at that. All that has been changed is the URL of the API, so that's strange.

This cooldown can be reset by simply opening the addon's menu and clicking save, by the way. This should tell it to attempt the API again.

The idea behind this was that the fallback actually worked when I initially created this addon, but TikTok has changed a lot since then, and directly opening or saving videos rarely seems to work now. So, if the API failed or needed updating, there was a fallback in place, and this stopped it from just infinitely attempting to use an API that may have not worked at all. But yeah, this doesn't seem to save any purpose anymore.

I think a good solution to this is to simply remove the fallback and the cooldown, and instead just have a better way of displaying an error or some sort whenever the API fails, as that seems to be the only reliable way of downloading videos now anyway. If I have some time soon, I may look into doing that.

**Comment by wombat2024** [comment]
Sure thanks @sixem take your time!

**Comment by jw-taylor** [comment]
> > Actually I sorta figured out a way to circumnavigate this situation, previously when I clicked the download button of certain video, if the download button hangs a few seconds spinning I know it's undownloadable (because usually it starts downloading instantly), then I could simply close that browser tab and reopen, and it'll not affect other videos to download.
> > However since the latest version when a video download fails it fails immediately (without button spinning), which makes it impossible for me to preemptively close the tab before it causes other videos to be undownloadable..
> 
> Yeah, once an API fails (it attempts a few times during the same download with a few different version parameters set), there will be a flag that tells it not to use the API until a set amount of time has passed. I think it's somewhere around 15 minutes. This is probably why it hangs on downloading, as it is attempting like 4-5 requests before giving up, I think, and when the flag/cooldown is active, this entire process is skipped. Why the behavior has changed since the last update, I don't know, and I'll have to have a look at that. All that has been changed is the URL of the API, so that's strange.
> 
> This cooldown can be reset by simply opening the addon's menu and clicking save, by the way. This should tell it to attempt the API again.
> 
> The idea behind this was that the fallback actually worked when I initially created this addon, but TikTok has changed a lot since then, and directly opening or saving videos rarely seems to work now. So, if the API failed or needed updating, there was a fallback in place, and this stopped it from just infinitely attempting to use an API that may have not worked at all. But yeah, this doesn't seem to save any purpose anymore.
> 
> I think a good solution to this is to simply remove the fallback and the cooldown, and instead just have a better way of displaying an error or some sort whenever the API fails, as that seems to be the only reliable way of downloading videos now anyway. If I have some time soon, I may look into doing that.

This appears to still be an issue for me now, but my version does say last updated 18 March

**Comment by sixem** [comment]
> > > Actually I sorta figured out a way to circumnavigate this situation, previously when I clicked the download button of certain video, if the download button hangs a few seconds spinning I know it's undownloadable (because usually it starts downloading instantly), then I could simply close that browser tab and reopen, and it'll not affect other videos to download.
> > > However since the latest version when a video download fails it fails immediately (without button spinning), which makes it impossible for me to preemptively close the tab before it causes other videos to be undownloadable..
> > 
> > 
> > Yeah, once an API fails (it attempts a few times during the same download with a few different version parameters set), there will be a flag that tells it not to use the API until a set amount of time has passed. I think it's somewhere around 15 minutes. This is probably why it hangs on downloading, as it is attempting like 4-5 requests before giving up, I think, and when the flag/cooldown is active, this entire process is skipped. Why the behavior has changed since the last update, I don't know, and I'll have to have a look at that. All that has been changed is the URL of the API, so that's strange.
> > This cooldown can be reset by simply opening the addon's menu and clicking save, by the way. This should tell it to attempt the API again.
> > The idea behind this was that the fallback actually worked when I initially created this addon, but TikTok has changed a lot since then, and directly opening or saving videos rarely seems to work now. So, if the API failed or needed updating, there was a fallback in place, and this stopped it from just infinitely attempting to use an API that may have not worked at all. But yeah, this doesn't seem to save any purpose anymore.
> > I think a good solution to this is to simply remove the fallback and the cooldown, and instead just have a better way of displaying an error or some sort whenever the API fails, as that seems to be the only reliable way of downloading videos now anyway. If I have some time soon, I may look into doing that.
> 
> This appears to still be an issue for me now, but my version does say last updated 18 March

Yeah, the API was broken again. There is a discussion about it here if you're curious:

[https://github.com/yt-dlp/yt-dlp/issues/9506](url)

I've updated it again now with the new information, and the API has worked for me during testing at least, but they're changing it more frequently now, so it may now live for much longer, we'll see. The issue you're seeing in the other issue you posted is just the fallback that's unreliable, and many of the requests made directly to the URL gets blocked, but when the API works correctly, it should work regardless through that.

**Comment by wombat2024** [comment]
Thanks @sixem just tried the latest version and it's brilliant 😁 actually I've found that the API failure rate also drops significantly, now barely see video fails to download, it used to be ~1/10
