### ISSUE TITLE
It seems tiktok detects this extention and blocks access 😢

### ISSUE THREAD

**Issue by wombat2024** [sixem/tiktok-download-buttons#21]
Just found this issue today, I tried both chrome and firefox, tiktok website works normal with this extension disabled, but after I enabled this extension, after a few refresh the whole page shows below error, which previously only happened once a while when download failed (and even when that happened the page browsing still works, now access is totally blocked to any page of tiktok domain), looks like tiktok dev team has targeted this extension 😭😡

```

Access Denied
You don't have permission to access "http://www.tiktok.com/@xxxxxxxxxx" on this server.
Reference #18.2758d617.1722788127.313659d7

https://errors.edgesuite.net/18.2758d617.1722788127.313659d7

```

**Comment by wombat2024** [comment]
screenshot

![Screen Shot 2024-08-05 at 02 20 49](https://github.com/user-attachments/assets/2cae7da6-3e04-4555-bb99-8a1e615d89ec)

**Comment by sixem** [comment]
Hi,

Hmm, this is strange. It works fine on my end. I can download and view the page normally with it enabled. Unfortunately, there's not much I can do without being able to reproduce this, but I'll definitely keep an eye on it going forward.

If anyone has any further input or ideas on why this could be happening, feel free to let me know and I'll gladly look into it.

**Comment by wombat2024** [comment]
@sixem ok very weird, turns out this particular user page caused this issue 🤯 I closed the tab and tried others all working fine, sorry to bother, closing now
