### ISSUE TITLE
Not working after recent Tiktok changes

### ISSUE THREAD

**Issue by halabiroger** [sixem/tiktok-download-buttons#23]
Hi, looks like the download button does not work on the main page of an account anymore after recent tiktok changes.  Just wanted to open this issue.

**Comment by sixem** [comment]
Hi,

Just to confirm: this is the small button in the top-right corner of the video previews, right? I’ve noticed that it doesn’t work for every video anymore (though it still works for some). I’ve looked into it and found a fix, and I'll try to get that out soon.

**Comment by halabiroger** [comment]
> Hi,
> 
> Just to confirm: this is the small button in the top-right corner of the video previews, right? I’ve noticed that it doesn’t work for every video anymore (though it still works for some). I’ve looked into it and found a fix, and I'll try to get that out soon.

Yes correct, the small button in the upper corner.

**Comment by sixem** [comment]
Hi,

Have you had a chance to try out the updated version? I've tested it on my end, and everything seems to work fine for me.

**Comment by halabiroger** [comment]
> Hi,
> 
> Have you had a chance to try out the updated version? I've tested it on my end, and everything seems to work fine for me.

Thank you very much for your efforts. Yes the new version is working great.

**Comment by sixem** [comment]
> > Hi,
> > Have you had a chance to try out the updated version? I've tested it on my end, and everything seems to work fine for me.
> 
> Thank you very much for your efforts. Yes the new version is working great.

Glad it's working, and thank you for bringing it up. If there's anything else, don't hesitate to open another issue :)
