### ISSUE TITLE
No "Download" button on single-video-view page

### ISSUE THREAD

**Issue by Lion-kh** [sixem/tiktok-download-buttons#26]
No "Download" button on single-video-view page - when only videoplayer on screen and comments under them. If comments right-side of the videoplayer - button exist.

**Comment by Lion-kh** [comment]
Details:
FireFox 133.0.3,
photo WITHOUT button:
![2024-12-27_193632](https://github.com/user-attachments/assets/da87d2db-ab95-41c1-9d6a-2abb03c1b5e6)

photo WITH button:
![2024-12-27_193545](https://github.com/user-attachments/assets/f0995d58-adab-4f49-8446-d66b8e8589f5)

**Comment by sixem** [comment]
Hi,

Thanks for letting me know. There seems to have been a change in the HTML layout. I'll look into this as soon as possible.

**Comment by Lion-kh** [comment]
Thank you very much for the prompt solution to the problem!
