### ISSUE TITLE
watermark is not hidden ... please help

### ISSUE THREAD

**Issue by MarkoTancos** [sixem/tiktok-download-buttons#5]
Hi i was using this extension maybe 3,4 days and it worked, now the videos dont have removed watermark ... can you update it or fix the issue?? BTW i appriciate the work you put into this , very well made ... thanks

**Comment by sixem** [comment]
Yea, you are right. It looks like it reverted to the default downloader because the API versions used were outdated. I've updated the API version now, see commit: b990dd0b91a80deb6618e724c12c0ba50262010b

I'll push the new update to Firefox and Chrome now. Hopefully that should fix it.

**Comment by MarkoTancos** [comment]
Thank you very much ... you did a great job if there will be any problem i will let you know ... love this extension ... god bless you
