### ISSUE TITLE
Thanks for this repository - (Not an actual issue)

### ISSUE THREAD

**Issue by Evil0ctal** [sixem/tiktok-download-buttons#6]
I just used the API in your js file in my repo, thanks for your work!

If you have time feel free and more then welcome to PR my repo!

Link: https://github.com/Evil0ctal/Douyin_TikTok_Download_API/

**Comment by sixem** [comment]
No problem, I'm glad it could help you too! Let's just hope this method keeps working for a while 😄

**Comment by Evil0ctal** [comment]
Yep :)
