### ISSUE TITLE
not able to download without without watermark i dont know how to use this thru github please help

### ISSUE THREAD

**Issue by Sanchitthegreat** [sixem/tiktok-download-buttons#8]
Let me know how to use the updated version of this app! I love this extension and its really helpful

also not able to download videos in full hd Thanks

**Comment by sixem** [comment]
The new version should be published on both Firefox and Chrome now. I pushed it through yesterday to Chrome, but it usually takes them a day or two to review it, but it should be reviewed and available now.

Also, regarding HD formats. It isn't available through the API anymore, so I can't do much about that.

Anyways, for the future, loading an addon from its source code can be done like this:

On Chrome you can go to extensions, enable `Developer mode` in the top-right corner and then click `Load unpacked`, then selecting the directory containing the source code of this repository.

On Firefox, you also go to the extensions, then debug addons (through the cogwheel menu), then `Load Temporary Addon`, and again selecting the directory or the location of the `manifest.json` of this source.

**Comment by Sanchitthegreat** [comment]
Hey really thanks for the Sixem, i just wanted one more help is there any way that when i download only the USERNAME is their on the file and not the whole username - caption. It would be awesome if you can help in this also is there any way we can support you?
