### ISSUE TITLE
Need one more help

### ISSUE THREAD

**Issue by Sanchitthegreat** [sixem/tiktok-download-buttons#9]
Hey really thanks for the Sixem, i just wanted one more help is there any way that when i download only the USERNAME is their on the file and not the whole username - caption. It would be awesome if you can help in this also is there any way we can support you?

**Comment by sixem** [comment]
At the moment there's only the default naming. Adding an option to customize the filename format shouldn't be too hard though, so I can look into adding this as a feature. I'm however a bit busy at the moment, so I can't promise I'll be adding this super soon, but I'll definitely keep it in mind, and do it when I have some spare time.

As for supporting me, there's no good way to do that. It's also not really necessary, so no worries about that, but thanks for the thought!

**Comment by halabiroger** [comment]
Hi, any new update on this?

**Comment by sixem** [comment]
> Hi, any new update on this?

I'll take a look at it this upcoming week.

**Comment by halabiroger** [comment]
> > Hi, any new update on this?
> 
> I'll take a look at it this upcoming week.

Thank you very much. Is there any opportunity to let us come up with our own naming convention?

**Comment by sixem** [comment]
> > > Hi, any new update on this?
> > 
> > 
> > I'll take a look at it this upcoming week.
> 
> Thank you very much. Is there any opportunity to let us come up with our own naming convention?

If doable, I'll try to just find a way to create custom naming templates. So, for example, using a template like:
```
{author}_{desc}-{id}
```
Would save an example video as: `RandomUser_RandomDescription-0123456789.mp4`. This would of course just be customized from the settings menu.

I think this is the best way of doing it? I'm open for any different ideas.

**Comment by sixem** [comment]
> > > > > Hi, any new update on this?
> > > > 
> > > > 
> > > > I'll take a look at it this upcoming week.
> > > 
> > > 
> > > Thank you very much. Is there any opportunity to let us come up with our own naming convention?
> > 
> > 
> > If doable, I'll try to just find a way to create custom naming templates. So, for example, using a template like:
> > ```
> > {author}_{desc}-{id}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would save an example video as: `RandomUser_RandomDescription-0123456789.mp4`. This would of course just be customized from the settings menu.
> > I think this is the best way of doing it? I'm open for any different ideas.
> 
> I think this would be great and looking forward to it. Can you also include date as a variable in the template?

The API responds with a unix timestamp which I'll include.

So far, the templating will look something like this, which is most of the relevant information that is fetchable from the API:
```json
{
    "uploader": "andreabotez",
    "nickname": "Andrea Botez",
    "desc": "only 2 weeks until my fight, feeling super confident 🦾",
    "uid": "6729585608039416837",
    "id": "7217247845525540139",
    "region": "US",
    "language": "en",
    "signature": "I play chess ♟",
    "timestamp": 1680396472
}
```
I can look into serving a readable timestamp as well if that's desirable, but I'm unsure of the format if that's the case... Maybe just something like `Apr 02 2023 00-47-52`?

Let me know if you have any more ideas.

**Comment by halabiroger** [comment]
> > > > > > Hi, any new update on this?
> > > > > 
> > > > > 
> > > > > I'll take a look at it this upcoming week.
> > > > 
> > > > 
> > > > Thank you very much. Is there any opportunity to let us come up with our own naming convention?
> > > 
> > > 
> > > If doable, I'll try to just find a way to create custom naming templates. So, for example, using a template like:
> > > ```
> > > {author}_{desc}-{id}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Would save an example video as: `RandomUser_RandomDescription-0123456789.mp4`. This would of course just be customized from the settings menu.
> > > I think this is the best way of doing it? I'm open for any different ideas.
> > 
> > 
> > I think this would be great and looking forward to it. Can you also include date as a variable in the template?
> 
> The API responds with a unix timestamp which I'll include (as well as a readable string of it).
> 
> So far, the templating will look something like this, which is most of the relevant information that is fetchable from the API:
> 
> ```json
> {
>     "uploader": "andreabotez",
>     "nickname": "Andrea Botez",
>     "desc": "only 2 weeks until my fight, feeling super confident 🦾",
>     "uid": "6729585608039416837",
>     "id": "7217247845525540139",
>     "region": "US",
>     "language": "en",
>     "signature": "I play chess ♟",
>     "uploaded": 1680396472,
>     "timestamp": 1680534350,
>     "uploaded_s": "20230402_024752",
>     "timestamp_s": "20230403_170550"
> }
> ```
> 
> Let me know if you have any more ideas.

This would be awesome.  Looking forward to you releasing an updated extension.

**Comment by halabiroger** [comment]
> > > > > > Hi, any new update on this?
> > > > > 
> > > > > 
> > > > > I'll take a look at it this upcoming week.
> > > > 
> > > > 
> > > > Thank you very much. Is there any opportunity to let us come up with our own naming convention?
> > > 
> > > 
> > > If doable, I'll try to just find a way to create custom naming templates. So, for example, using a template like:
> > > ```
> > > {author}_{desc}-{id}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Would save an example video as: `RandomUser_RandomDescription-0123456789.mp4`. This would of course just be customized from the settings menu.
> > > I think this is the best way of doing it? I'm open for any different ideas.
> > 
> > 
> > I think this would be great and looking forward to it. Can you also include date as a variable in the template?
> 
> The API responds with a unix timestamp which I'll include (as well as a readable string of it).
> 
> So far, the templating will look something like this, which is most of the relevant information that is fetchable from the API:
> 
> ```json
> {
>     "uploader": "andreabotez",
>     "nickname": "Andrea Botez",
>     "desc": "only 2 weeks until my fight, feeling super confident 🦾",
>     "uid": "6729585608039416837",
>     "id": "7217247845525540139",
>     "region": "US",
>     "language": "en",
>     "signature": "I play chess ♟",
>     "uploaded": 1680396472,
>     "timestamp": 1680534350,
>     "uploaded_s": "20230402_024752",
>     "timestamp_s": "20230403_170550"
> }
> ```
> 
> Let me know if you have any more ideas.

Not trying to rush you, but just curious when you might implement this and update the extension?

**Comment by sixem** [comment]
> Not trying to rush you, but just curious when you might implement this and update the extension?

The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.

**Comment by halabiroger** [comment]
> > Not trying to rush you, but just curious when you might implement this and update the extension?
> 
> The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.

Thx I will wait for you to update the Chrome extension store since I don't know how to use the updated github repository files.

**Comment by sixem** [comment]
> > > Not trying to rush you, but just curious when you might implement this and update the extension?
> > 
> > 
> > The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.
> 
> Thx I will wait for you to update the Chrome extension store since I don't know how to use the updated github repository files.

You can download the repository, go to extensions in Chrome, enable `Developer mode` in the top-right corner and then `Load unpacked` from there, selecting the repository files.

It would be nice if you could confirm that it's working for you, but if not, that's fine too. I'll test it a bit more myself regardless!

**Comment by halabiroger** [comment]
> > > > Not trying to rush you, but just curious when you might implement this and update the extension?
> > > 
> > > 
> > > The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.
> > 
> > 
> > Thx I will wait for you to update the Chrome extension store since I don't know how to use the updated github repository files.
> 
> You can download the repository, go to extensions in Chrome, enable `Developer mode` in the top-right corner and then `Load unpacked` from there, selecting the repository files.
> 
> It would be nice if you could confirm that it's working for you, but if not, that's fine too. I'll test it a bit more myself regardless!

Sorry for my ignorance, but how do I download the repository?  I am not a Github expert.

**Comment by sixem** [comment]
> > > > > Not trying to rush you, but just curious when you might implement this and update the extension?
> > > > 
> > > > 
> > > > The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.
> > > 
> > > 
> > > Thx I will wait for you to update the Chrome extension store since I don't know how to use the updated github repository files.
> > 
> > 
> > You can download the repository, go to extensions in Chrome, enable `Developer mode` in the top-right corner and then `Load unpacked` from there, selecting the repository files.
> > It would be nice if you could confirm that it's working for you, but if not, that's fine too. I'll test it a bit more myself regardless!
> 
> Sorry for my ignorance, but how do I download the repository? I am not a Github expert.

Just download the zip of the master branch should work: [https://github.com/sixem/tiktok-download-buttons/archive/refs/heads/main.zip](https://github.com/sixem/tiktok-download-buttons/archive/refs/heads/main.zip)

Anway, no need to test it if you are unexperienced with it. It's not a big deal. I ran some tests on a Linux machine today which worked fine, so I think I'll just go ahead and push the update tonight.

**Comment by halabiroger** [comment]
> > > > > > Not trying to rush you, but just curious when you might implement this and update the extension?
> > > > > 
> > > > > 
> > > > > The feature has been pushed to the repository, so you are free to test it if you want to. I'll just have to test it a bit more on different platforms, then I'll submit and update which usually takes anywhere from an hour to a few days. I'll see if I can do that later today, or at the latest tomorrow.
> > > > 
> > > > 
> > > > Thx I will wait for you to update the Chrome extension store since I don't know how to use the updated github repository files.
> > > 
> > > 
> > > You can download the repository, go to extensions in Chrome, enable `Developer mode` in the top-right corner and then `Load unpacked` from there, selecting the repository files.
> > > It would be nice if you could confirm that it's working for you, but if not, that's fine too. I'll test it a bit more myself regardless!
> > 
> > 
> > Sorry for my ignorance, but how do I download the repository? I am not a Github expert.
> 
> Just download the zip of the master branch should work: https://github.com/sixem/tiktok-download-buttons/archive/refs/heads/main.zip
> 
> Anyway, no need to test it if you are unexperienced with it. It's not a big deal. I ran some tests on a Linux machine today which worked fine, so I think I'll just go ahead and push the update tonight.

Thank you, I appreciate all your efforts.

**Comment by sixem** [comment]
> Thank you, I appreciate all your efforts.

No problem! I've submitted the update now. It's live on Firefox, but Chrome will probably take some more time to pass the review process.

If either @Sanchitthegreat (if you are still around) or @halabiroger could let me know that it's working as expected when it's live, that'd be great, so that I can mark it as solved! :)

**Comment by halabiroger** [comment]
> > > Thank you, I appreciate all your efforts.
> > 
> > 
> > No problem! I've submitted the update now. It's live on Firefox, but Chrome will probably take some more time to pass the review process.
> > If either @Sanchitthegreat (if you are still around) or @halabiroger could let me know that it's working as expected when it's live, that'd be great, so that I can mark it as solved! :)
> 
> Thank you very much, but I still don't see the new version yet in the Chrome store. I will keep checking.

How long does the Chrome web store take to update?

**Comment by halabiroger** [comment]
> > > > > Thank you, I appreciate all your efforts.
> > > > 
> > > > 
> > > > No problem! I've submitted the update now. It's live on Firefox, but Chrome will probably take some more time to pass the review process.
> > > > If either @Sanchitthegreat (if you are still around) or @halabiroger could let me know that it's working as expected when it's live, that'd be great, so that I can mark it as solved! :)
> > > 
> > > 
> > > Thank you very much, but I still don't see the new version yet in the Chrome store. I will keep checking.
> > 
> > 
> > How long does the Chrome web store take to update?
> 
> Like I said above, anywhere from a few hours to a few days. Google is a bit more strict than Mozilla when it comes to pushing out updates et cetera.

Thx I will keep waiting.

**Comment by halabiroger** [comment]
> > Thank you, I appreciate all your efforts.
> 
> No problem! I've submitted the update now. It's live on Firefox, but Chrome will probably take some more time to pass the review process.
> 
> If either @Sanchitthegreat (if you are still around) or @halabiroger could let me know that it's working as expected when it's live, that'd be great, so that I can mark it as solved! :)

I have the new extension now and it works great. Thx for all your time and effort.

**Comment by sixem** [comment]
> > > Thank you, I appreciate all your efforts.
> > 
> > 
> > No problem! I've submitted the update now. It's live on Firefox, but Chrome will probably take some more time to pass the review process.
> > If either @Sanchitthegreat (if you are still around) or @halabiroger could let me know that it's working as expected when it's live, that'd be great, so that I can mark it as solved! :)
> 
> I have the new extension now and it works great. Thx for all your time and effort.

No problem. Good to hear that it's working!
